/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 259b4a7f0121a28f74f29fdc464ca0a6)
interface __BaseEnv_Env {
	PHOTOS: R2Bucket;
	EMAIL: SendEmail;
	EMAIL_FROM: "verify@pull-up.davisbrown.dev";
	WEB_ORIGIN: "https://pull-up.davisbrown.dev";
	CLOUDFLARE_ACCOUNT_ID: "720bb9fc6dc82b02f5612a450a8d6ebf";
	DATABASE_URL: string;
	JWT_SECRET: string;
	UPLOAD_SIGNING_SECRET: string;
	INTERNAL_TASK_SECRET: string;
	API_CONTAINER: DurableObjectNamespace<import("./src/index").ApiContainer>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "ApiContainer";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "EMAIL_FROM" | "WEB_ORIGIN" | "CLOUDFLARE_ACCOUNT_ID" | "DATABASE_URL" | "JWT_SECRET" | "UPLOAD_SIGNING_SECRET" | "INTERNAL_TASK_SECRET">> {}
}
